[package]
name = "ci-gen"
version = "0.0.0"
authors = ["Stiopa Koltsov <stepan.koltsov@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
gh-actions-gen = { git = "https://github.com/stepancheg/gh-actions-gen", rev = "162ef71bb703b97eca86dc474b3d3d0a972097ad" }
#gh-actions-gen = { path = "../../gh-actions-gen/gh-actions-gen" }
